 -- GENERATES A DAY ROW for 730 days
with CTE_DATE_GENERATOR as (
    select DATEADD(DAY, SEQ4() * -1, CURRENT_DATE) as DAY_ROW
    from table(GENERATOR(ROWCOUNT => 730) )

)

select
    TO_DATE(DAY_ROW) as DATE,
    YEAR(DAY_ROW) as YEAR,
    QUARTER(DAY_ROW) as QUARTER,
    MONTH(DAY_ROW) as MONTH_NUM,
    MONTHNAME(DAY_ROW) as MONTH_NAME,
    WEEKOFYEAR(DAY_ROW) as WEEK_NUM,
    DAY(DAY_ROW) as DAY_NUM,
    DAYNAME(DAY_ROW) as DAY_NAME,
    DAYOFWEEK(DAY_ROW) as DAY_OF_WEEK,
    DAYOFYEAR(DAY_ROW) as DAY_OF_YEAR
from CTE_DATE_GENERATOR
